dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    python: "3.8-dev"
    python: "nightly"
    
    
# Needed in travis to allow install of scipy package
before_install:
  - sudo apt-get -y install libblas-dev  liblapack-dev

# command to install dependencies
install:
  - pip install pandas
  - pip install git+https://github.com/blampe/IbPy.git
  - pip install scipy
  - pip install statsmodels
# - pip install your_package


# command to run tests
script: cd tests && nosetests -v -v
